var penguin  = require('./dao/link')

penguin.initial(1)
penguin.listall(1)
penguin.addfunc("Malmo")
penguin.addfunc("Stockholm")
penguin.addfunc("Stockholm")
penguin.addfunc("Malmo")
penguin.addfunc("Stockholm")
penguin.addfunc("Stockholm")
penguin.addfunc("Stockholm")
penguin.addfunc("Malmo")
penguin.listall(1)
console.log(penguin.check("Stockholm"))
console.log(penguin.check("Kiruna"))
